FROM {{ .BaseImage }}

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN apk add --no-cache gettext
WORKDIR /server
COPY server.jar ./
COPY plugins/ plugins/
{{ range .Files -}}
COPY {{ .Src }} {{ .MountPath }}
{{ end -}}
RUN ls plugins/*.jar 1>/dev/null 2>&1 && cp -r plugins/ .embedded-plugins/ || true

ENTRYPOINT ["/entrypoint.sh"]
